admin_controllers:
  name_prefix: admin_
  resource: ../src/Http/Admin/Controller
  type: annotation

seller_controllers:
  name_prefix: seller_
  resource: ../src/Http/Seller/Controller
  type: annotation

controllers:
  resource: ../src/Http/Controller
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation